version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:8080"
    links:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
